#!/usr/bin/env sh

# Usage:
# `$0`: Ask for recording type via dmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.

RECORDPID_DIR=/tmp/recordpidid.d
STATUSBAR=i3blocks
mkdir -p ${RECORDPID_DIR}

updateicon() { \
	echo "$1" > /tmp/recordingicon
	pkill -RTMIN+9 "${STATUSBAR:?}"
	}

killrecording() {
	for recordpidfile in ${RECORDPID_DIR}/* ; do
		recpid=$(cat ${recordpidfile})
        echo "Stopping process $recpid"
		# kill with SIGTERM, allowing finishing touches.
		kill -15 "$recpid"
		rm -f ${recordpidfile}
		pkill -RTMIN+9 "${STATUSBAR:?}"
		# even after SIGTERM, ffmpeg may still run, so SIGKILL it.
		sleep 3
		kill -9 "$recpid"
	done
	updateicon ""
	exit
	}

screencast() { \
	ffmpeg -y \
	-f x11grab \
	-framerate 60 \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
	-f alsa -i default \
	-r 30 \
	-c:v libx264rgb -crf 0 -preset ultrafast -c:a flac \
	"$HOME/Video/screencast-$(date '+%y%m%d-%H%M-%S').mkv" &
	echo $! > ${RECORDPID_DIR}/scr-recordpid-$(ls -1q ${RECORDPID_DIR}/ | wc -l)
	updateicon "⏺️🎙️"
       	}

video() { ffmpeg \
	-f x11grab \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
 	-c:v libx264 -qp 0 -r 30 \
	"$HOME/Video/video-$(date '+%y%m%d-%H%M-%S').mkv" &
	echo $! > ${RECORDPID_DIR}/vid-recordpid-$(ls -1q ${RECORDPID_DIR}/ | wc -l)
	updateicon "⏺️"
	}

webcamhidef() { ffmpeg \
	-f v4l2 \
	-i /dev/video0 \
	-video_size 1920x1080 \
	"$HOME/Video/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
	echo $! > ${RECORDPID_DIR}/wcam-recordpid-$(ls -1q ${RECORDPID_DIR}/ | wc -l)
	updateicon "🎥"
	}

webcam() { ffmpeg \
	-f v4l2 \
	-i /dev/video0 \
	-video_size 640x480 \
	"$HOME/Video/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
	echo $! > ${RECORDPID_DIR}/wcamhi-recordpid-$(ls -1q ${RECORDPID_DIR}/ | wc -l)
	updateicon "🎥"
	}


audio() { \
	ffmpeg \
	-f alsa -i default \
	-c:a flac \
	"$HOME/Video/audio-$(date '+%y%m%d-%H%M-%S').flac" &
	echo $! > ${RECORDPID_DIR}/audio-recordpid-$(ls -1q ${RECORDPID_DIR}/ | wc -l)
	updateicon "🎙️"
	}

askrecording() { \
	choice=$(printf "all\\nscreencast\\nvideo\\naudio\\nwebcam\\nwebcam (hi-def)" | dmenu -i -p "Select recording style:")
	case "$choice" in
		all) screencast & webcamhidef;;
		screencast) screencast;;
		audio) audio;;
		video) video;;
		webcam) webcam;;
		"webcam (hi-def)") webcamhidef;;
	esac
	}

asktoend() { \
	response=$(printf "No\\nYes" | dmenu -i -p "Recording still active. End recording?") &&
	[ "$response" = "Yes" ] &&  killrecording
	}


case "$1" in
	screencast) screencast;;
	audio) audio;;
	video) video;;
	kill) killrecording;;
	webcam) webcam;;
	"webcam (hi-def)") webcamhidef;;
	*) ([ $(ls -1q ${RECORDPID_DIR}/ | wc -l) -gt 0 ] && asktoend && exit) || askrecording;;
esac
