#!/bin/bash

echo "starting peakblue"

# Bluetooth addr
MDR_XB70BT="00:18:09:94:14:7F"
dev_addr=$MDR_XB70BT

# First warm up the bluetooth interface with blueman
blueman-manager &> /dev/null & blueman_pid=$!
sleep 2
kill "$blueman_pid"

echo "Attempting to connect to : $dev_addr"

# Run the initial commands for powering and scanning etc
coproc bluetoothctl
echo -e 'agent on\ndefault-agent\npower on\nscan on\n' >&${COPROC[1]}
echo -e 'info $dev_addr\n' >&${COPROC[1]}
echo -e 'connect $dev_addr\nexit' >&${COPROC[1]}
output=$(cat <&${COPROC[0]})
echo $output

sleep 4

while :
do
  # Attempt to connect
  coproc bluetoothctl
  echo -e 'connect $dev_addr\n' >&${COPROC[1]}
  echo -e 'info $dev_addr\nexit' >&${COPROC[1]}
  output=$(cat <&${COPROC[0]})
  echo $output
  sleep 4

  # Check for successful connection or loop
  if [[ $output == *"Connected: yes"* ]]; then
    echo "Successfully connected to $dev_addr"
    # echo $output
    break
  fi
done

echo "exiting"
