#!/usr/bin/env bash

TEMPLATEDIR=$HOME/.templates

cp_template() { cp -r "$(du -a -d 1 $1/ | awk '{print $2}' | fzf)" . ;}

[ -z $1 ] && cp_template "$(du -a -d 1 $TEMPLATEDIR | awk '{print $2}' | fzf)" || cp_template $TEMPLATEDIR/$1
