#!/usr/bin/env sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

# calculate cpu usage as 100 - idle
n=$(top -n 1 -b | awk '/%Cpu\(s\):/ {print $8}')
let cpu_usage=100-${n%.*}
# Get the cpu temperature
cpu_temp=$(sensors | awk '/Core 0/ {print $3}')

echo " %$cpu_usage $cpu_temp"
