#!/usr/bin/env bash

PIQUEINDEX=~/Documents/personal/pique/index.csv
PIQUELOGS=~/Documents/personal/pique/logs.csv


piq_ls() # Shows the index of shirts
{
    cat $PIQUEINDEX
}

piq_new() # Logs a new shirt
{
    id=$(wc -l <$PIQUEINDEX)
    color=$1
    pattern=$2
    url=$3
    echo "$id,$color,$pattern,$url" >> $PIQUEINDEX
}

piq_log() # Logs a new wear of shirt
{
    piq_id=$1
    DATE=`date +%Y-%m-%d`
    echo "$DATE,$piq_id" >> $PIQUELOGS
}
