#!/usr/bin/env bash

# GET ARGS
while getopts ":r:f:hl" o; do case "${o}" in
	h) 
    echo -e "Optional arguments for custom use:"
    echo -e "  -f: File"
    echo -e "  -r: Retreive number"
    echo -e "  -l: Worker program to call"
    echo -e "  -h: Show this message"
    exit 
    ;;
	f) openFile="$openFile ${OPTARG}" ;;
	r) retreiveNum=${OPTARG} ;;
	l) list="true" ;; # Flag, sets var true
	*) echo "-$OPTARG is not a valid option." && exit ;;
esac done

# DEFAULTS:
[ -z ${cachefile+x} ] && cachefile=$HOME/.scripts/.workcache.csv && touch $cachefile
[ -z ${retreiveNum+x} ] && retreiveNum=$(wc -l <$cachefile)
[ -z ${openFile+x} ] && openFile="false"
[ -z ${list+x} ] && list="false"
# Debug one of the params
echo "cachefile is : $cachefile"
echo "retreivenum is : $retreiveNum"

wrl()
{
    less $cachefile
}

wrw()
{
    # Get dir
    current_wd=$(pwd)
    echo "Saving workdir for $current_wd"
    # Program path
    retreiveNum=$((1 + $(wc -l <$cachefile)))
    echo "$retreiveNum,$current_wd,$@" >> $cachefile
}

wro()
{
	while IFS=, read -r num workpath files; do
      if [ "$1" = "$num" ];then
        cd $workpath 
        openfiles="$files"
      fi
	done < $cachefile ;
    # Open files in vim
    if [[ -z {$openfiles+x} ]]; then
      echo "Index invalid or didnt have files"
    else 
      eval "vim -O ${openfiles}"
    fi
}

# PROGRAM START
main () 
{
    # List files if it is set
    [[ $list = "true" ]] && wrl && exit

    if [ "$openFile" = "false" ]; then echo "Proceeding to workdir lookup"; else
        wrw $openFile
        exit
    fi

    # Retreive
    wro $retreiveNum
}
[[ $_ != $0 ]] && echo "Script is being sourced" || main $@
